/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * 
 */

package com.projects;

import java.util.Scanner;

public class P002 {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		int pp = 1;
		int p = 2;
		
		int sum = p;
		int term = 0;
		
		do {
			term = p + pp;
			
			pp = p;
			p = term; 
			
			if(term % 2 == 0) {
				sum = sum + term;
			}
			
		} while(term <= 4_000_000);	
		System.out.println(sum);
	}

}
